
submit_ticket:
    path:     /tickets/submit
    defaults: { _controller: AppBundle:Sales:submitTicket }

ticket_submission_successful:
    path:     /tickets/submit/success
    defaults: { _controller: AppBundle:Sales:ticketSubmissionSuccessful }

submit_user:
    path:     /users/submit
    defaults: { _controller: AppBundle:Users:submitUser }

user_submission_successful:
    path:     /users/submit/success
    defaults: { _controller: AppBundle:Sales:Users }
